CREATE TABLE [dbo].[tblComplaint] (
    [Id]                    UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [ComplainantId]         UNIQUEIDENTIFIER NOT NULL,
    [ComplainantType]       INT              NOT NULL,
    [ComplainedAgainstId]   UNIQUEIDENTIFIER NOT NULL,
    [ComplainedAgainstType] INT              NOT NULL,
    [FranchiseId]           UNIQUEIDENTIFIER NULL,
    [Title]                 NVARCHAR (200)   NOT NULL,
    [Description]           NVARCHAR (2000)  NOT NULL,
    [Category]              INT              NULL,
    [Severity]              INT              NULL,
    [Status]                INT              DEFAULT ((1)) NOT NULL,
    [Resolution]            NVARCHAR (2000)  NULL,
    [ResolutionDate]        DATETIME         NULL,
    [ResolvedBy]            UNIQUEIDENTIFIER NULL,
    [CreatedDate]           DATETIME         DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]           DATETIME         NULL,
    [CreatedBy]             UNIQUEIDENTIFIER NULL,
    [UpdatedBy]             UNIQUEIDENTIFIER NULL,
    [IsActive]              BIT              DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_tblComplaint] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_tblComplaint_Complainant] FOREIGN KEY ([ComplainantId]) REFERENCES [dbo].[tblUser] ([Id]),
    CONSTRAINT [FK_tblComplaint_ComplainedAgainst] FOREIGN KEY ([ComplainedAgainstId]) REFERENCES [dbo].[tblUser] ([Id]),
    CONSTRAINT [FK_tblComplaint_Franchise] FOREIGN KEY ([FranchiseId]) REFERENCES [dbo].[tblFranchise] ([Id]),
    CONSTRAINT [FK_tblComplaint_ResolvedBy] FOREIGN KEY ([ResolvedBy]) REFERENCES [dbo].[tblUser] ([Id])
);

